[2024-09-21T16:56:34.153+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-21T16:56:34.186+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: localNFLDataIngestionDag.ingestData manual__2024-09-21T16:55:45.395890+00:00 [queued]>
[2024-09-21T16:56:34.200+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: localNFLDataIngestionDag.ingestData manual__2024-09-21T16:55:45.395890+00:00 [queued]>
[2024-09-21T16:56:34.201+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-09-21T16:56:34.236+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): ingestData> on 2024-09-21 16:55:45.395890+00:00
[2024-09-21T16:56:34.248+0000] {standard_task_runner.py:72} INFO - Started process 532 to run task
[2024-09-21T16:56:34.254+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'localNFLDataIngestionDag', 'ingestData', 'manual__2024-09-21T16:55:45.395890+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpmuiged6y']
[2024-09-21T16:56:34.257+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask ingestData
[2024-09-21T16:56:34.326+0000] {task_command.py:467} INFO - Running <TaskInstance: localNFLDataIngestionDag.ingestData manual__2024-09-21T16:55:45.395890+00:00 [running]> on host a38c0324a413
[2024-09-21T16:56:34.425+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='localNFLDataIngestionDag' AIRFLOW_CTX_TASK_ID='ingestData' AIRFLOW_CTX_EXECUTION_DATE='2024-09-21T16:55:45.395890+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-21T16:55:45.395890+00:00'
[2024-09-21T16:56:34.427+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-21T16:56:34.429+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-21T16:56:34.430+0000] {logging_mixin.py:190} INFO - Current task name:ingestData state:running start_date:2024-09-21 16:56:34.187610+00:00
[2024-09-21T16:56:34.431+0000] {logging_mixin.py:190} INFO - Dag name:localNFLDataIngestionDag and current dag run status:running
[2024-09-21T16:56:34.432+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-21T16:56:34.436+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/ingestNFLData.py", line 14, in ingest_weekly_data
    df = pd.read_csv(csv_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/weekly_nfl_data_2024-09-21.csv'
[2024-09-21T16:56:34.454+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-21T16:56:34.455+0000] {logging_mixin.py:190} INFO - Task start:2024-09-21 16:56:34.187610+00:00 end:2024-09-21 16:56:34.453399+00:00 duration:0.265789
[2024-09-21T16:56:34.457+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): ingestData> dag:<DAG: localNFLDataIngestionDag> dagrun:<DagRun localNFLDataIngestionDag @ 2024-09-21 16:55:45.395890+00:00: manual__2024-09-21T16:55:45.395890+00:00, state:running, queued_at: 2024-09-21 16:56:29.971589+00:00. externally triggered: True>
[2024-09-21T16:56:34.458+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/opt/***/weekly_nfl_data_2024-09-21.csv'
[2024-09-21T16:56:34.459+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=localNFLDataIngestionDag, task_id=ingestData, run_id=manual__2024-09-21T16:55:45.395890+00:00, execution_date=20240921T165545, start_date=20240921T165634, end_date=20240921T165634
[2024-09-21T16:56:34.476+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-21T16:56:34.478+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task ingestData ([Errno 2] No such file or directory: '/opt/airflow/weekly_nfl_data_2024-09-21.csv'; 532)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/ingestNFLData.py", line 14, in ingest_weekly_data
    df = pd.read_csv(csv_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/weekly_nfl_data_2024-09-21.csv'
[2024-09-21T16:56:34.509+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-21T16:56:34.527+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-21T16:56:34.531+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
